[features]
seeds      = false
skip-lint  = false
resolution = true

[programs.localnet]
croptopia = "Crptp111111111111111111111111111111111111"

[programs.devnet]
croptopia = "Crptp111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet  = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types   = "target/types"
members = ["programs/*"]
